"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ....
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


class Problem2:
    @staticmethod
    def sum_of_even_fibonacci_numbers(limit: int = 4000000) -> None:
        number_1: int = 1
        number_2: int = 2
        total: int = 0
        while number_1 <= limit:
            if number_1 % 2 == 0:
                total += number_1
            number_1, number_2 = number_2, number_1 + number_2
        print(total)


if __name__ == "__main__":
    app: Problem2 = Problem2()
    app.sum_of_even_fibonacci_numbers()
